version: '3'

services:
#  db:
#    image: postgres:latest
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5432:5432"
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /code/db
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A EventManager worker --loglevel=info
    volumes:
      - .:/code
      - /code/db
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"